# Generated by Django 4.1.1 on 2022-09-12 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=120, verbose_name='Evento')),
                ('pick', models.CharField(max_length=120, verbose_name='Pick')),
                ('amount', models.FloatField(verbose_name='Apuesta')),
                ('quote', models.FloatField(verbose_name='Cuota')),
                ('result', models.CharField(blank=True, choices=[('w', 'W'), ('l', 'L'), ('n', 'N')], max_length=5, verbose_name='W/L/N')),
                ('result_desc', models.CharField(blank=True, max_length=150, verbose_name='Resultado')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingresos.type', verbose_name='Tipo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_bank', models.FloatField()),
                ('bank', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
