# Generated by Django 4.1.1 on 2022-09-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0003_alter_bet_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='quote',
            new_name='odd',
        ),
    ]
