# Generated by Django 4.1.1 on 2022-09-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0005_bet_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bank',
            field=models.FloatField(blank=True, default=1000, verbose_name='Bank'),
            preserve_default=False,
        ),
    ]
